spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
#    url: jdbc:h2: jdbc:mysql://localhost:3330/withpet?useSSL=false&serverTimezone=Asia/Seoul
#    driver-class-name:  com.mysql.cj.jdbc.Driver
#    username: root
#    password: ''
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
server:
  port: 8888